version: "3.1"

services:
  mysql:
    image: mysql:5.7.22
    container_name: dev_mysql_untilla
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: work_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
